# Generated by Django 5.0.1 on 2024-03-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_automa', '0002_pedido_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
    ]
