# Generated by Django 5.0.1 on 2024-03-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='username',
            new_name='usuario',
        ),
    ]
